"""reset class Post default value

Revision ID: 187cd015bc08
Revises: b6ca199fc27a
Create Date: 2017-12-09 17:58:55.772000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187cd015bc08'
down_revision = 'b6ca199fc27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'visits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'posts', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'visits',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
