"""add visits server_default

Revision ID: b6ca199fc27a
Revises: 938de4f63b0c
Create Date: 2017-12-06 22:46:34.128000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ca199fc27a'
down_revision = '938de4f63b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'visits',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'posts', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'visits',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
